export const REFRESH_MENU = 'REFRESH_MENU';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'ADD_ITEM_FROM_CART';
export const UPDATE_USER_PHONE = 'UPDATE_USER_PHONE';
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN';
export const STORE_AUTH_TOKEN = 'STORE_AUTH_TOKEN';
export const PURGE_CART = 'PURGE_CART';
